/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * KeyForge API
 * OpenAPI spec version: 0.1.0
 */
import type { ContentRequestDifficulty } from './contentRequestDifficulty';

export interface ContentRequest {
  /** english | coding | hindi | placement | resume | government */
  mode: string;
  /** python | java | javascript | cpp | c | mysql | html | css | english | hindi | oops | dbms | ... */
  language: string;
  difficulty?: ContentRequestDifficulty;
  linesCount?: number;
  /**
     * Specific topic for placement/government modes
     * @nullable
     */
  topic?: string | null;
}
