/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * KeyForge API
 * OpenAPI spec version: 0.1.0
 */

export interface FeedbackRequest {
  wpm: number;
  accuracy: number;
  errors: number;
  duration: number;
  mode: string;
  language: string;
  /** @nullable */
  targetWpm?: number | null;
}
