/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI TypeRacer API
 * OpenAPI spec version: 0.1.0
 */

export type GetLeaderboardPeriod = typeof GetLeaderboardPeriod[keyof typeof GetLeaderboardPeriod];


export const GetLeaderboardPeriod = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
  all_time: 'all_time',
} as const;
