/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI TypeRacer API
 * OpenAPI spec version: 0.1.0
 */
import type { GetLeaderboardPeriod } from './getLeaderboardPeriod';

export type GetLeaderboardParams = {
category?: string;
period?: GetLeaderboardPeriod;
limit?: number;
};
