/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI TypeRacer API
 * OpenAPI spec version: 0.1.0
 */

export interface PlatformStats {
  totalUsers: number;
  totalTests: number;
  highestWpm: number;
  languagesSupported: number;
}
