/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * KeyForge API
 * OpenAPI spec version: 0.1.0
 */
import type { ModeStats } from './modeStats';

export interface StatsSummary {
  bestWpm: number;
  averageWpm: number;
  totalTests: number;
  averageAccuracy: number;
  bestAccuracy: number;
  byMode?: ModeStats[];
}
