/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * KeyForge API
 * OpenAPI spec version: 0.1.0
 */

export interface TrendPoint {
  date: string;
  wpm: number;
  accuracy: number;
}
