/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * KeyForge API
 * OpenAPI spec version: 0.1.0
 */

export interface TypingTestInput {
  username: string;
  mode: string;
  language: string;
  wpm: number;
  accuracy: number;
  errors: number;
  duration: number;
  /** @nullable */
  linesCount?: number | null;
  /** @nullable */
  codeTheme?: string | null;
}
