/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI TypeRacer API
 * OpenAPI spec version: 0.1.0
 */

export interface TypingTest {
  id: number;
  username: string;
  /** english | coding | hindi | hindi_english | blind | placement | resume | government */
  mode: string;
  /** The specific language or subject (e.g. python, java, hindi, english) */
  language: string;
  wpm: number;
  accuracy: number;
  errors: number;
  /** Duration in seconds */
  duration: number;
  /** @nullable */
  linesCount?: number | null;
  /** @nullable */
  codeTheme?: string | null;
  createdAt: Date;
}
