/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI TypeRacer API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List recent typing test results
 */
export const listTypingTestsQueryLimitDefault = 20;

export const ListTypingTestsQueryParams = zod.object({
  "limit": zod.coerce.number().default(listTypingTestsQueryLimitDefault),
  "mode": zod.coerce.string().optional()
})

export const ListTypingTestsResponseItem = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "mode": zod.string().describe('english | coding | hindi | hindi_english | blind | placement | resume | government'),
  "language": zod.string().describe('The specific language or subject (e.g. python, java, hindi, english)'),
  "wpm": zod.number(),
  "accuracy": zod.number(),
  "errors": zod.number(),
  "duration": zod.number().describe('Duration in seconds'),
  "linesCount": zod.number().nullish(),
  "codeTheme": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListTypingTestsResponse = zod.array(ListTypingTestsResponseItem)


/**
 * @summary Save a completed typing test result
 */
export const CreateTypingTestBody = zod.object({
  "username": zod.string(),
  "mode": zod.string(),
  "language": zod.string(),
  "wpm": zod.number(),
  "accuracy": zod.number(),
  "errors": zod.number(),
  "duration": zod.number(),
  "linesCount": zod.number().nullish(),
  "codeTheme": zod.string().nullish()
})


/**
 * @summary Get a specific typing test result
 */
export const GetTypingTestParams = zod.object({
  "id": zod.coerce.number()
})

export const GetTypingTestResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "mode": zod.string().describe('english | coding | hindi | hindi_english | blind | placement | resume | government'),
  "language": zod.string().describe('The specific language or subject (e.g. python, java, hindi, english)'),
  "wpm": zod.number(),
  "accuracy": zod.number(),
  "errors": zod.number(),
  "duration": zod.number().describe('Duration in seconds'),
  "linesCount": zod.number().nullish(),
  "codeTheme": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get aggregated user performance summary
 */
export const GetStatsSummaryQueryParams = zod.object({
  "username": zod.coerce.string().optional()
})

export const GetStatsSummaryResponse = zod.object({
  "bestWpm": zod.number(),
  "averageWpm": zod.number(),
  "totalTests": zod.number(),
  "averageAccuracy": zod.number(),
  "bestAccuracy": zod.number(),
  "byMode": zod.array(zod.object({
  "mode": zod.string(),
  "bestWpm": zod.number(),
  "averageWpm": zod.number(),
  "totalTests": zod.number()
})).optional()
})


/**
 * @summary Get WPM and accuracy trends over time
 */
export const getStatsTrendsQueryDaysDefault = 30;

export const GetStatsTrendsQueryParams = zod.object({
  "username": zod.coerce.string().optional(),
  "mode": zod.coerce.string().optional(),
  "days": zod.coerce.number().default(getStatsTrendsQueryDaysDefault)
})

export const GetStatsTrendsResponseItem = zod.object({
  "date": zod.string(),
  "wpm": zod.number(),
  "accuracy": zod.number()
})
export const GetStatsTrendsResponse = zod.array(GetStatsTrendsResponseItem)


/**
 * @summary Get leaderboard entries
 */
export const getLeaderboardQueryCategoryDefault = `overall`;
export const getLeaderboardQueryPeriodDefault = `all_time`;
export const getLeaderboardQueryLimitDefault = 50;

export const GetLeaderboardQueryParams = zod.object({
  "category": zod.coerce.string().default(getLeaderboardQueryCategoryDefault),
  "period": zod.enum(['daily', 'weekly', 'monthly', 'all_time']).default(getLeaderboardQueryPeriodDefault),
  "limit": zod.coerce.number().default(getLeaderboardQueryLimitDefault)
})

export const GetLeaderboardResponseItem = zod.object({
  "rank": zod.number(),
  "username": zod.string(),
  "wpm": zod.number(),
  "accuracy": zod.number(),
  "mode": zod.string(),
  "language": zod.string().optional(),
  "createdAt": zod.coerce.date()
})
export const GetLeaderboardResponse = zod.array(GetLeaderboardResponseItem)


/**
 * @summary Generate AI typing content for a given mode and language
 */
export const generateContentBodyDifficultyDefault = `intermediate`;
export const generateContentBodyLinesCountDefault = 30;

export const GenerateContentBody = zod.object({
  "mode": zod.string().describe('english | coding | hindi | placement | resume | government'),
  "language": zod.string().describe('python | java | javascript | cpp | c | mysql | html | css | english | hindi | oops | dbms | ...'),
  "difficulty": zod.enum(['beginner', 'intermediate', 'advanced']).default(generateContentBodyDifficultyDefault),
  "linesCount": zod.number().default(generateContentBodyLinesCountDefault),
  "topic": zod.string().nullish().describe('Specific topic for placement\/government modes')
})

export const GenerateContentResponse = zod.object({
  "text": zod.string(),
  "language": zod.string(),
  "mode": zod.string(),
  "title": zod.string().nullish()
})


/**
 * @summary Generate AI coaching feedback after a completed test
 */
export const GenerateFeedbackBody = zod.object({
  "wpm": zod.number(),
  "accuracy": zod.number(),
  "errors": zod.number(),
  "duration": zod.number(),
  "mode": zod.string(),
  "language": zod.string(),
  "targetWpm": zod.number().nullish()
})

export const GenerateFeedbackResponse = zod.object({
  "strengths": zod.array(zod.string()),
  "weaknesses": zod.array(zod.string()),
  "suggestions": zod.array(zod.string()),
  "targetWpm": zod.number(),
  "summary": zod.string().optional()
})


/**
 * @summary Get platform-wide live statistics (total users, tests, highest WPM, languages)
 */
export const GetPlatformStatsResponse = zod.object({
  "totalUsers": zod.number(),
  "totalTests": zod.number(),
  "highestWpm": zod.number(),
  "languagesSupported": zod.number()
})


